#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: shuffle-service-conf
  labels:
    {{- include "remote-shuffle-service.labels" . | nindent 4 }}
data:
  rss-defaults.conf: |-
    {{- range $key, $val := .Values.rss }}
    {{ $key }}={{ $val }}
    {{- end -}} 
    {{- $namespace  := .Release.Namespace }}
    rss.ha.enabled=true
    rss.ha.service.id=rss
    rss.ha.master.hosts={{ range until (.Values.masterReplicas |int) }}shuffleservice-master-{{ . }}.rss-master-svc.{{ $namespace }}.svc.cluster.local,{{ end }}
    rss.ha.nodes.rss={{ range until (.Values.masterReplicas |int) }}node{{ . }},{{ end }}
    {{- range until (.Values.masterReplicas |int) }}
    rss.ha.address.rss.node{{ . }}=shuffleservice-master-{{ . }}.rss-master-svc.{{ $namespace }}.svc.cluster.local
    {{- end }}
    
  rss-env.sh: |
    {{- range $key, $val := .Values.environments }}
    {{ $key }}="{{ $val }}"
    {{- end}} 

  log4j.properties: |-
    # Set everything to be logged to the console
    log4j.rootCategory=INFO, console
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.target=System.err
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

  metrics.properties: >-
    *.sink.prometheusServlet.class=com.aliyun.emr.rss.common.metrics.sink.PrometheusServlet
